### ISSUE TITLE
Unavailability of contributing guidelines.

### ISSUE THREAD

**Issue by khyatigoyal** [reactos/developer-web-interface#5]
The guidelines for the contribution is unavailable also the Readme file doesn't have the description about the project and the steps for deployment of the project on localhost is unavailable.

**Comment by ayushsnha** [comment]
@khyatigoyal  This project isn't looking for any contributor for now because it comes under my GSoC project. After GSoC 2019 the project will be open for contributions also readme and deployment instructions will be included after GSoC. Check the repository again after a month :)  for other details and queries feel free to join https://chat.reactos.org the official reactOS discussion forum

**Comment by khyatigoyal** [comment]
Ohk Thankyou for the information.
